#!/usr/bin/bash

cd # run in user dir

# sudo w/o password
echo '"${whoami}" ALL=(ALL) NOPASSWD:ALL' | sudo EDITOR="tee -a" visudo

# zsh

apt install zsh
zsh
chsh -s $(which zsh)

# wget and curl

apt install wget
apt install curl

# git(hub)

# Assumes you have already been logged into git

apt install git
git config --global user.email "proofprogram@gmail.com"
git config --global user.name "Dennis Chen"
git config --global credential.helper store

snap install gh
gh auth login

# Install some apps that I use

apt install vim
snap install discord
snap install code --classic
snap install spotify

# Node and NPM (through nvm)

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | zsh
nvm install node

# TeX Live

## Install
apt install perl-tk # TeX uses perl
wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
tar -xzf install-tl-unx.tar.gz
cd "install-tl-$(date +%Y%m%d)"
./install-tl
cd

## Clone Dennis Chen repos

./bin/dtex clone

## Get CTANzip
cd bin
git clone https://github.com/chennisden/ctanzip
