set tabstop=2
set autoindent
set shiftwidth=2

set number
set relativenumber

" Vim-plug

let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
	silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
	autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
	Plug 'chennisden/markdown-preview.nvim', { 'do': 'cd app && yarn install'  }
	Plug 'preservim/nerdtree'
	" NerdTree extensions
	Plug 'Xuyuanp/nerdtree-git-plugin'
	Plug 'ryanoasis/vim-devicons'
call plug#end()

" Auto-start NERDTREE if no arg (ie no file opened)
" and move cursor to other window
" autocmd VimEnter * NERDTree | if argc() > 0 || exists("s:std_in") | wincmd p | endif
